//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMediaApp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostLikeRequest
    {
        public int PostLikeRequestId { get; set; }
        public int PostId { get; set; }
        public int UserId { get; set; }
        public string LikeType { get; set; }
    
        public virtual UserPost UserPost { get; set; }
        public virtual UserData UserData { get; set; }
    }
}
